# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: 'Checkout Code'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRm'
    azureSubscription: 'Azure for Students'
    appType:'webAppWindows'
    WebAppName:'CCSE2152233'
    RuntimeStack: 'PHP|8.2'
  displayName: 'Deploy to Azure Web App'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
